[tool.poetry]
name = "modulo ii"
version = "0.1.0"
description = "Entrega del modulo 2"
authors = ["Valeria Hdez"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
